/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Enhanced with animation controls
*/

'use client';

import * as THREE from 'three'
import { useRef, useMemo, useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

// All available animations
export type AnimationName = 
  | 'Attack(1h)' | 'AttackCombo' | 'AttackSpinning' | 'BasePose' | 'Block' 
  | 'Cheer' | 'Climbing' | 'Dance' | 'DashBack' | 'DashFront' | 'DashLeft' 
  | 'DashRight' | 'Defeat' | 'HeavyAttack' | 'Hop' | 'Idle' | 'Interact' 
  | 'Jump_Idle' | 'Jump' | 'Jump_Land' | 'Jump_Start' | 'LayingDownIdle' 
  | 'PickUp' | 'Roll' | 'Run' | 'Shoot(1h)' | 'Shoot(2h)' | 'Shoot(2h)Bow' 
  | 'Shooting(1h)' | 'Shooting(2h)' | 'Throw' | 'Walk' | 'Wave'

interface GLTFAction extends THREE.AnimationClip {
  name: AnimationName
}

type GLTFResult = GLTF & {
  nodes: {
    mug_1: THREE.Mesh
    mug_1_1: THREE.Mesh
    mug_1_2: THREE.Mesh
    outline: THREE.SkinnedMesh
    PrototypePete: THREE.SkinnedMesh
    Body: THREE.Bone
  }
  materials: {
    brownDark: THREE.MeshStandardMaterial
    greyLight: THREE.MeshStandardMaterial
    outline: THREE.MeshStandardMaterial
    PrototypePete: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export interface CharacterProps {
  animation?: AnimationName
  color?: string
  characterScale?: number
}

type GroupProps = React.ComponentProps<'group'>

export function Character({ 
  animation = 'Idle', 
  color,
  characterScale = 0.5,
  ...props 
}: CharacterProps & GroupProps) {
  const group = useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/Floating Character.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  
  // Store previous animation for crossfade
  const prevAnimationRef = useRef<AnimationName>(animation)

  // Handle animation changes with crossfade
  useEffect(() => {
    const currentAction = actions[animation]
    const prevAction = actions[prevAnimationRef.current]

    if (currentAction) {
      // Crossfade from previous to current
      if (prevAction && prevAction !== currentAction) {
        prevAction.fadeOut(0.2)
      }
      
      currentAction
        .reset()
        .setEffectiveTimeScale(1)
        .setEffectiveWeight(1)
        .fadeIn(0.2)
        .play()

      prevAnimationRef.current = animation
    }

    return () => {
      currentAction?.fadeOut(0.2)
    }
  }, [animation, actions])

  // Apply custom color if provided
  useEffect(() => {
    if (color && materials.PrototypePete) {
      materials.PrototypePete.color.set(color)
    }
  }, [color, materials])

  return (
    <group ref={group} {...props} dispose={null} scale={characterScale}>
      <group name="Scene">
        <group name="KayKit_Animated_Character">
          <primitive object={nodes.Body} />
          <skinnedMesh 
            name="outline" 
            geometry={nodes.outline.geometry} 
            material={materials.outline} 
            skeleton={nodes.outline.skeleton}
            frustumCulled
          />
          <skinnedMesh 
            name="PrototypePete" 
            geometry={nodes.PrototypePete.geometry} 
            material={materials.PrototypePete} 
            skeleton={nodes.PrototypePete.skeleton}
            frustumCulled
          />
        </group>
      </group>
    </group>
  )
}

// Preload the model
useGLTF.preload('/Floating Character.glb')

// Export animation names for easy access
export const ANIMATIONS: AnimationName[] = [
  'Idle', 'Walk', 'Run', 'Jump', 'Jump_Start', 'Jump_Idle', 'Jump_Land',
  'Attack(1h)', 'AttackCombo', 'AttackSpinning', 'HeavyAttack',
  'Block', 'Roll', 'DashFront', 'DashBack', 'DashLeft', 'DashRight',
  'Dance', 'Cheer', 'Wave', 'Defeat', 'Hop',
  'Shoot(1h)', 'Shoot(2h)', 'Shoot(2h)Bow', 'Shooting(1h)', 'Shooting(2h)',
  'Climbing', 'Interact', 'PickUp', 'Throw', 'LayingDownIdle', 'BasePose'
]
