/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/low_poly_forest_4_optimized.glb -o src/components/game/ForestMap.tsx -t -k 
Author: Digital screen official (https://sketchfab.com/ck212575)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-forest-4-e7114cfd53a341459db4e66fd6a280c8
Title: low poly forest 4
*/


import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

type ForestMapProps = {
  scale?: number;
  position?: [number, number, number];
} & React.ComponentProps<'group'>;

export function ForestMap({ scale = 1, position = [0, 0, 0], ...props }: ForestMapProps) {
  const { nodes, materials } = useGLTF('/low_poly_forest_4_optimized.glb') as unknown as GLTFResult;
  // Use MeshBasicMaterial for best performance (no lighting calculation)
  const basicMaterial = React.useMemo(() => {
    // Use color from original material if available
    const color = materials.Material.color || new THREE.Color(0x228B22);
    return new THREE.MeshBasicMaterial({ color, side: THREE.FrontSide });
  }, [materials.Material]);

  return (
    <group {...props} dispose={null} position={position} scale={scale}>
      <mesh
        name="Object_2"
        geometry={nodes.Object_2.geometry}
        material={basicMaterial}
        rotation={[-Math.PI / 2, 0, 0]}
        frustumCulled
        castShadow={false}
        receiveShadow={false}
      />
    </group>
  );
}

useGLTF.preload('/low_poly_forest_4_optimized.glb')
