/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Digital screen official (https://sketchfab.com/ck212575)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-forest-4-e7114cfd53a341459db4e66fd6a280c8
Title: low poly forest 4
*/

'use client';

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useMemo } from 'react'
import * as BufferGeometryUtils from 'three/examples/jsm/utils/BufferGeometryUtils.js'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

interface ForestMapProps {
  scale?: number
  position?: [number, number, number]
}

type GroupProps = React.ComponentProps<'group'>

export function ForestMap({ 
  scale = 1,
  position = [0, 0, 0],
  ...props 
}: ForestMapProps & GroupProps) {
  const { nodes, materials } = useGLTF('/low_poly_forest_4.glb') as unknown as GLTFResult
  
  // Super simple material - MeshBasicMaterial tidak perlu lighting calculation
  const basicMaterial = useMemo(() => {
    // Ambil warna dari original material
    const color = materials.Material.color || new THREE.Color(0x228B22)
    return new THREE.MeshBasicMaterial({ 
      color,
      side: THREE.FrontSide,
    })
  }, [materials.Material])

  // Merge geometries properly using Three.js utility
  const mergedGeometry = useMemo(() => {
    const geos = [
      nodes.Object_2.geometry.clone(),
      nodes.Object_3.geometry.clone(),
      nodes.Object_4.geometry.clone(),
    ]
    
    // Pastikan semua geometry punya attributes yang sama
    geos.forEach(geo => {
      // Hapus attributes yang tidak perlu untuk reduce memory
      if (geo.attributes.uv) geo.deleteAttribute('uv')
      if (geo.attributes.uv2) geo.deleteAttribute('uv2')
    })
    
    const merged = BufferGeometryUtils.mergeGeometries(geos, false)
    merged.computeBoundingSphere()
    return merged
  }, [nodes])
  
  return (
    <group {...props} dispose={null} position={position}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={scale}>
        <mesh 
          name="ForestMap_Merged" 
          geometry={mergedGeometry} 
          material={basicMaterial}
          frustumCulled
        />
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_forest_4.glb')
